services:
  rplotter:
    build: 
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - R_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
      - PLUMBER_DEV=FALSE
      - LOG_HTTP=true
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs:
